version: '2'
services:
  node:
    image: node:carbon
    working_dir: /app
    command: npm start
    environment:
      - PORT=8080
      - NODE_ENV=development
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./app:/app
  db:
    image: postgres:9
    environment:
      POSTGRES_DB: mtaadb
      POSTGRES_USER: mtaa
      POSTGRES_PASSWORD: Kie5deinah1ooriThiecheemaebohy7d
    expose:
      - 5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - /var/lib/postgresql/data
      - ./db/dump:/dump
