version: '2'
services:
  node:
    image: node:carbon
    working_dir: /app
    command: npm start
    environment:
      - PORT=8080
      - NODE_ENV=development
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./app:/app
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: mtaadb
      MYSQL_USER: mtaa
      MYSQL_PASSWORD: Kie5deinah1ooriThiecheemaebohy7d
      MYSQL_ROOT_PASSWORD: Kie5deinah1ooriThiecheemaebohy7d
    expose:
      - 3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/dump:/dump
