version: '2'
services:
  db:
    image: postgres:9
    environment:
      POSTGRES_DB: mtaadb
      POSTGRES_USER: mtaa
      POSTGRES_PASSWORD: Kie5deinah1ooriThiecheemaebohy7d
    expose:
      - 5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
      - ./db/dump:/dump
